### ISSUE TITLE
Examples would be helpful

### ISSUE THREAD

**Issue by bytearchive** [vintasoftware/classy-django-rest-framework#32]
If you add an example to each class like a hello-world to use it, that would really help

I would not have to search internet again to use your class

**Comment by fjsj** [comment]
Hi, thanks for the issue. We're closing this because the original goal of CDRF is not to replace the original DRF documentation, but to provide an easy way of checking the class members of classes that DRF users commonly need to override. CDRF is inspired by http://ccbv.co.uk/
