### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by napsterv** [vintasoftware/classy-django-rest-framework#33]
Any chance of an update to DRF 3.11 and .12

**Comment by chocoelho** [comment]
Hey there.

Yes, there are. First we'll need to tackle #25 in order to be able to add these versions as otherwise the build breaks. They should be added throughout the next quarter.

**Comment by napsterv** [comment]
Alright👍👍 Thanks for the prompt response.

**Comment by fjsj** [comment]
we're working on updates on the next couple of weeks, thanks!

**Comment by napsterv** [comment]
> we're working on updates on the next couple of weeks, thanks!

This is great news, thanks for the progress update! :)
