### ISSUE TITLE
cdrf.co not resolving

### ISSUE THREAD

**Issue by juanjgarcia** [vintasoftware/classy-django-rest-framework#34]
Thanks for the work this - I've found it extremely useful. Unfortunately I've noticed the main website has been down for a while. Just making you aware. Thanks!

**Comment by filipeximenes** [comment]
@juanjgarcia perhaps your browser is redirecting you to https? It currently only works at http://www.cdrf.co/. 
In any case this is definitely something we should get fixed.

**Comment by juanjgarcia** [comment]
Bingo, `https-everywhere` was redirecting. Would be nice to have it on https. I'll add an exclusion. Sorry should have checked that!

**Comment by urkh** [comment]
the website seems to be down again

**Comment by fjsj** [comment]
Those seem to be minor issues that were already solved
