### ISSUE TITLE
I'm not sure if this should be here!

### ISSUE THREAD

**Issue by Janus-sama** [vintasoftware/classy-django-rest-framework#46]
I think there's a backward compatibility with the `MarkupSafe==2.0.1` - `soft_unicode` has been removed for `soft_str`.

Basically, the build fails because the `soft_unicode` cannot be imported (obviously!).

I'd make probably open this issue in `Jinja2` too.

**Comment by fjsj** [comment]
Hi @Janus-sama, could you please make a PR with a fix?

**Comment by Janus-sama** [comment]
Done
