### ISSUE TITLE
Proper Attribution & License check

### ISSUE THREAD

**Issue by itdependsnetworks** [vintasoftware/classy-django-rest-framework#55]
Hi, based on your work, I have put together: https://github.com/itdependsnetworks/mkdocs-python-classy

It's basically using your inspector logic, but letting mkdocs manage everything else. I wanted to ensure that I have correctly provided attribution and license

You can see the associated documentation at:
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/README.md#attribution
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/NOTICE
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/LICENSE
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/docs/dev/attribution.md

**Comment by fjsj** [comment]
LGTM. Thanks!
